baseUrl=https://www.enuygun.com
petstoreBaseUrl=https://petstore.swagger.io/v2

browser=chrome
headless=false

fromCity=Istanbul
toCity=Ankara

departureTimeFilterStart=10:00
departureTimeFilterEnd=18:00
